import { db } from './database.js';
import bcrypt from 'bcryptjs';

export function seedDatabase() {
  console.log('🌱 Seeding One Family demo data (Sharma Family)...');

  const familyId = 'fam_sharma_01';

  // 1. Family
  const families = [
    {
      id: familyId,
      name: 'Sharma Family',
      family_key: 'FAM-SHARMA-01',
      photo_url: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?w=600&auto=format&fit=crop&q=80',
      location: 'Hyderabad, India',
      currency: 'INR',
      language: 'en',
      created_at: new Date('2024-01-01').toISOString(),
      updated_at: new Date().toISOString(),
    },
  ];

  // 2. Users / Family Members
  const users = [
    {
      id: 'usr_raj',
      family_id: familyId,
      email: 'raj.sharma@example.com',
      phone: '+91 98765 43210',
      name: 'Raj Sharma',
      password_hash: bcrypt.hashSync('1234', 10),
      pin_code: bcrypt.hashSync('1234', 10),
      avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
      role: 'FAMILY_HEAD',
      relationship: 'Self / Father',
      birth_date: '1985-06-15',
      created_at: new Date('2024-01-01').toISOString(),
    },
    {
      id: 'usr_priya',
      family_id: familyId,
      email: 'priya.sharma@example.com',
      phone: '+91 98765 43211',
      name: 'Priya Sharma',
      password_hash: bcrypt.hashSync('1234', 10),
      pin_code: bcrypt.hashSync('1234', 10),
      avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
      role: 'SPOUSE',
      relationship: 'Spouse / Mother',
      birth_date: '1988-09-22',
      created_at: new Date('2024-01-01').toISOString(),
    },
    {
      id: 'usr_aarav',
      family_id: familyId,
      email: 'aarav.sharma@example.com',
      phone: '+91 98765 43212',
      name: 'Aarav Sharma',
      password_hash: bcrypt.hashSync('1234', 10),
      pin_code: bcrypt.hashSync('1234', 10),
      avatar_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
      role: 'CHILD',
      relationship: 'Son (14 yrs)',
      birth_date: '2012-04-10',
      created_at: new Date('2024-01-01').toISOString(),
    },
    {
      id: 'usr_ananya',
      family_id: familyId,
      email: 'ananya.sharma@example.com',
      phone: '+91 98765 43213',
      name: 'Ananya Sharma',
      password_hash: bcrypt.hashSync('1234', 10),
      pin_code: bcrypt.hashSync('1234', 10),
      avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80',
      role: 'CHILD',
      relationship: 'Daughter (8 yrs)',
      birth_date: '2018-11-05',
      created_at: new Date('2024-01-01').toISOString(),
    },
    {
      id: 'usr_kalyani',
      family_id: familyId,
      email: 'kalyani.sharma@example.com',
      phone: '+91 98765 43214',
      name: 'Kalyani Sharma',
      password_hash: bcrypt.hashSync('1234', 10),
      pin_code: bcrypt.hashSync('1234', 10),
      avatar_url: 'https://images.unsplash.com/photo-1581579438747-1dc8d17bbce4?w=200&auto=format&fit=crop&q=80',
      role: 'VIEWER',
      relationship: 'Grandmother (68 yrs)',
      birth_date: '1958-02-28',
      created_at: new Date('2024-01-01').toISOString(),
    },
  ];

  // 3. Permissions
  const permissionsList = [
    { id: 'p1', code: 'FINANCE_VIEW', name: 'View Family Finances', category: 'FINANCE' },
    { id: 'p2', code: 'FINANCE_EDIT', name: 'Manage Family Finances', category: 'FINANCE' },
    { id: 'p3', code: 'INVESTMENT_VIEW', name: 'View Investments & Net Worth', category: 'INVESTMENT' },
    { id: 'p4', code: 'INVESTMENT_EDIT', name: 'Manage Investments', category: 'INVESTMENT' },
    { id: 'p5', code: 'DOCUMENT_VIEW', name: 'View Documents', category: 'DOCUMENT' },
    { id: 'p6', code: 'DOCUMENT_UPLOAD', name: 'Upload Documents', category: 'DOCUMENT' },
    { id: 'p7', code: 'DOCUMENT_DELETE', name: 'Delete Documents', category: 'DOCUMENT' },
    { id: 'p8', code: 'EMERGENCY_VIEW', name: 'View Emergency Vault', category: 'EMERGENCY' },
    { id: 'p9', code: 'EMERGENCY_EDIT', name: 'Manage Emergency Vault', category: 'EMERGENCY' },
    { id: 'p10', code: 'MEMORY_VIEW', name: 'View Memories & Albums', category: 'MEMORY' },
    { id: 'p11', code: 'MEMORY_UPLOAD', name: 'Upload Memories', category: 'MEMORY' },
    { id: 'p12', code: 'CALENDAR_VIEW', name: 'View Calendar', category: 'CALENDAR' },
    { id: 'p13', code: 'CALENDAR_EDIT', name: 'Manage Events', category: 'CALENDAR' },
    { id: 'p14', code: 'TASK_VIEW', name: 'View Tasks & Grocery', category: 'TASK' },
    { id: 'p15', code: 'TASK_EDIT', name: 'Manage Tasks', category: 'TASK' },
    { id: 'p16', code: 'AI_USE', name: 'Use Family AI Assistant', category: 'AI' },
    { id: 'p17', code: 'FAMILY_MANAGE', name: 'Manage Family & Members', category: 'ADMIN' },
  ];

  const allCodes = permissionsList.map((p) => p.code);
  const childCodes = ['CALENDAR_VIEW', 'CALENDAR_EDIT', 'TASK_VIEW', 'TASK_EDIT', 'MEMORY_VIEW', 'MEMORY_UPLOAD', 'AI_USE'];
  const viewerCodes = ['CALENDAR_VIEW', 'MEMORY_VIEW', 'MEMORY_UPLOAD', 'EMERGENCY_VIEW', 'AI_USE'];

  const memberPermissions: any[] = [];
  allCodes.forEach((code) => {
    memberPermissions.push({ user_id: 'usr_raj', permission_code: code });
    memberPermissions.push({ user_id: 'usr_priya', permission_code: code });
  });
  childCodes.forEach((code) => {
    memberPermissions.push({ user_id: 'usr_aarav', permission_code: code });
    memberPermissions.push({ user_id: 'usr_ananya', permission_code: code });
  });
  viewerCodes.forEach((code) => {
    memberPermissions.push({ user_id: 'usr_kalyani', permission_code: code });
  });

  // 4. Expense Categories
  const expenseCategories = [
    { id: 'cat_groceries', family_id: familyId, name: 'Groceries', icon: 'ShoppingCart', color: '#10B981' },
    { id: 'cat_dining', family_id: familyId, name: 'Food & Dining', icon: 'Utensils', color: '#F59E0B' },
    { id: 'cat_utilities', family_id: familyId, name: 'Utilities & Bills', icon: 'Zap', color: '#6366F1' },
    { id: 'cat_rent', family_id: familyId, name: 'Rent & Maintenance', icon: 'Home', color: '#8B5CF6' },
    { id: 'cat_education', family_id: familyId, name: 'Education & School', icon: 'GraduationCap', color: '#EC4899' },
    { id: 'cat_transport', family_id: familyId, name: 'Transport & Fuel', icon: 'Car', color: '#3B82F6' },
    { id: 'cat_healthcare', family_id: familyId, name: 'Healthcare & Medicine', icon: 'HeartPulse', color: '#EF4444' },
    { id: 'cat_shopping', family_id: familyId, name: 'Shopping', icon: 'ShoppingBag', color: '#14B8A6' },
    { id: 'cat_entertainment', family_id: familyId, name: 'Entertainment', icon: 'Film', color: '#F97316' },
    { id: 'cat_travel', family_id: familyId, name: 'Travel & Trips', icon: 'Plane', color: '#06B6D4' },
    { id: 'cat_insurance', family_id: familyId, name: 'Insurance Premiums', icon: 'ShieldCheck', color: '#059669' },
    { id: 'cat_investments', family_id: familyId, name: 'Investments / SIP', icon: 'TrendingUp', color: '#4F46E5' },
    { id: 'cat_emi', family_id: familyId, name: 'Loan EMI', icon: 'CreditCard', color: '#7C3AED' },
    { id: 'cat_misc', family_id: familyId, name: 'Miscellaneous', icon: 'MoreHorizontal', color: '#64748B' },
  ];

  // 5. Budgets (Current Month)
  const currentMonth = '2026-09';
  const budgets = [
    { id: 'b_1', family_id: familyId, category_id: 'cat_groceries', category_name: 'Groceries', monthly_limit: 15000, month_year: currentMonth, created_at: new Date().toISOString() },
    { id: 'b_2', family_id: familyId, category_id: 'cat_dining', category_name: 'Food & Dining', monthly_limit: 8000, month_year: currentMonth, created_at: new Date().toISOString() },
    { id: 'b_3', family_id: familyId, category_id: 'cat_utilities', category_name: 'Utilities & Bills', monthly_limit: 5000, month_year: currentMonth, created_at: new Date().toISOString() },
    { id: 'b_4', family_id: familyId, category_id: 'cat_rent', category_name: 'Rent & Maintenance', monthly_limit: 25000, month_year: currentMonth, created_at: new Date().toISOString() },
    { id: 'b_5', family_id: familyId, category_id: 'cat_education', category_name: 'Education & School', monthly_limit: 20000, month_year: currentMonth, created_at: new Date().toISOString() },
    { id: 'b_6', family_id: familyId, category_id: 'cat_transport', category_name: 'Transport & Fuel', monthly_limit: 6000, month_year: currentMonth, created_at: new Date().toISOString() },
    { id: 'b_7', family_id: familyId, category_id: 'cat_healthcare', category_name: 'Healthcare & Medicine', monthly_limit: 4000, month_year: currentMonth, created_at: new Date().toISOString() },
    { id: 'b_8', family_id: familyId, category_id: 'cat_shopping', category_name: 'Shopping', monthly_limit: 10000, month_year: currentMonth, created_at: new Date().toISOString() },
  ];

  // 6. Expenses
  const expenses = [
    {
      id: 'exp_1',
      family_id: familyId,
      user_id: 'usr_priya',
      paid_by_name: 'Priya',
      category_id: 'cat_groceries',
      category_name: 'Groceries',
      amount: 14200,
      currency: 'INR',
      date: '2026-09-04',
      payment_method: 'UPI',
      merchant: 'Ratnadeep Supermarket',
      notes: 'Monthly staples, dry fruits and cooking oils',
      location: 'Gachibowli, Hyderabad',
      receipt_url: 'https://images.unsplash.com/photo-1554415707-9e49666ceb24?w=400',
      split_type: 'EQUAL',
      created_at: '2026-09-04T11:20:00Z',
    },
    {
      id: 'exp_2',
      family_id: familyId,
      user_id: 'usr_raj',
      paid_by_name: 'Raj',
      category_id: 'cat_rent',
      category_name: 'Rent & Maintenance',
      amount: 25000,
      currency: 'INR',
      date: '2026-09-01',
      payment_method: 'BANK_TRANSFER',
      merchant: 'Aparna CyberLife Society',
      notes: 'Flat maintenance & monthly advance',
      location: 'Nallagandla',
      receipt_url: '',
      split_type: 'EQUAL',
      created_at: '2026-09-01T09:00:00Z',
    },
    {
      id: 'exp_3',
      family_id: familyId,
      user_id: 'usr_raj',
      paid_by_name: 'Raj',
      category_id: 'cat_education',
      category_name: 'Education & School',
      amount: 18000,
      currency: 'INR',
      date: '2026-09-02',
      payment_method: 'CREDIT_CARD',
      merchant: 'Oakridge International School',
      notes: 'Term 2 activity and bus fee for Aarav & Ananya',
      location: 'Gachibowli',
      receipt_url: '',
      split_type: 'EQUAL',
      created_at: '2026-09-02T14:30:00Z',
    },
    {
      id: 'exp_4',
      family_id: familyId,
      user_id: 'usr_priya',
      paid_by_name: 'Priya',
      category_id: 'cat_dining',
      category_name: 'Food & Dining',
      amount: 6800,
      currency: 'INR',
      date: '2026-09-06',
      payment_method: 'UPI',
      merchant: 'Chutneys Restaurant & Swiggy',
      notes: 'Weekend family dinner & delivery',
      location: 'Hitec City',
      receipt_url: '',
      split_type: 'EQUAL',
      created_at: '2026-09-06T20:15:00Z',
    },
    {
      id: 'exp_5',
      family_id: familyId,
      user_id: 'usr_raj',
      paid_by_name: 'Raj',
      category_id: 'cat_transport',
      category_name: 'Transport & Fuel',
      amount: 4500,
      currency: 'INR',
      date: '2026-09-05',
      payment_method: 'CREDIT_CARD',
      merchant: 'Indian Oil Petrol Pump',
      notes: 'Full tank for Honda City + Fastag recharge',
      location: 'Kondapur',
      receipt_url: '',
      split_type: 'EQUAL',
      created_at: '2026-09-05T18:00:00Z',
    },
    {
      id: 'exp_6',
      family_id: familyId,
      user_id: 'usr_priya',
      paid_by_name: 'Priya',
      category_id: 'cat_healthcare',
      category_name: 'Healthcare & Medicine',
      amount: 2100,
      currency: 'INR',
      date: '2026-09-07',
      payment_method: 'UPI',
      merchant: 'Apollo Pharmacy',
      notes: 'Grandmother blood pressure medicines and multivitamins',
      location: 'Madhapur',
      receipt_url: '',
      split_type: 'EQUAL',
      created_at: '2026-09-07T10:00:00Z',
    },
    {
      id: 'exp_7',
      family_id: familyId,
      user_id: 'usr_raj',
      paid_by_name: 'Raj',
      category_id: 'cat_shopping',
      category_name: 'Shopping',
      amount: 5600,
      currency: 'INR',
      date: '2026-09-08',
      payment_method: 'UPI',
      merchant: 'Amazon India',
      notes: 'School stationery & kitchen organizer',
      location: 'Online',
      receipt_url: '',
      split_type: 'EQUAL',
      created_at: '2026-09-08T16:45:00Z',
    },
    {
      id: 'exp_8',
      family_id: familyId,
      user_id: 'usr_raj',
      paid_by_name: 'Raj',
      category_id: 'cat_utilities',
      category_name: 'Utilities & Bills',
      amount: 2250,
      currency: 'INR',
      date: '2026-09-03',
      payment_method: 'UPI',
      merchant: 'Airtel Fiber Broadband',
      notes: 'Home fiber internet 3-month plan',
      location: 'Hyderabad',
      receipt_url: '',
      split_type: 'EQUAL',
      created_at: '2026-09-03T09:30:00Z',
    },
  ];

  // 7. Investments (Assets)
  const investments = [
    {
      id: 'inv_1',
      family_id: familyId,
      user_id: 'usr_raj',
      owner_name: 'Raj Sharma',
      type: 'MUTUAL_FUND',
      title: 'Parag Parikh Flexi Cap Fund',
      institution: 'PPFAS Mutual Fund',
      invested_amount: 800000,
      current_value: 1250000,
      gain_loss: 450000,
      folio_number: '10928374/2',
      nominee: 'Priya Sharma (100%)',
      notes: 'Monthly SIP ₹15,000 active',
      updated_at: '2026-09-01T00:00:00Z',
    },
    {
      id: 'inv_2',
      family_id: familyId,
      user_id: 'usr_priya',
      owner_name: 'Priya Sharma',
      type: 'MUTUAL_FUND',
      title: 'Mirae Asset Large Cap Fund',
      institution: 'Mirae Asset AMC',
      invested_amount: 450000,
      current_value: 600000,
      gain_loss: 150000,
      folio_number: '99281726/1',
      nominee: 'Raj Sharma (100%)',
      notes: 'Monthly SIP ₹10,000 active',
      updated_at: '2026-09-01T00:00:00Z',
    },
    {
      id: 'inv_3',
      family_id: familyId,
      user_id: 'usr_raj',
      owner_name: 'Raj Sharma',
      type: 'STOCK',
      title: 'Direct Equity Portfolio (TCS, Infosys, Reliance)',
      institution: 'Zerodha Kite',
      invested_amount: 650000,
      current_value: 920000,
      gain_loss: 270000,
      folio_number: '120816000293847',
      nominee: 'Priya Sharma',
      notes: 'Blue chip long term dividend stocks',
      updated_at: '2026-09-08T00:00:00Z',
    },
    {
      id: 'inv_4',
      family_id: familyId,
      user_id: 'usr_raj',
      owner_name: 'Raj & Priya',
      type: 'FIXED_DEPOSIT',
      title: 'SBI Cumulative Fixed Deposit',
      institution: 'State Bank of India',
      invested_amount: 450000,
      current_value: 500000,
      gain_loss: 50000,
      maturity_date: '2026-09-24',
      folio_number: 'SBI-FD-482910',
      nominee: 'Aarav Sharma',
      notes: 'Maturing in 15 days! Rate 7.2% p.a.',
      updated_at: '2026-09-01T00:00:00Z',
    },
    {
      id: 'inv_5',
      family_id: familyId,
      user_id: 'usr_priya',
      owner_name: 'Priya Sharma',
      type: 'GOLD',
      title: 'Sovereign Gold Bonds (SGB 2021-22)',
      institution: 'RBI / HDFC Sec',
      invested_amount: 320000,
      current_value: 480000,
      gain_loss: 160000,
      folio_number: 'SGB-2021-HYD',
      nominee: 'Ananya Sharma',
      notes: '60 grams gold equivalence + 2.5% semi-annual interest',
      updated_at: '2026-09-01T00:00:00Z',
    },
    {
      id: 'inv_6',
      family_id: familyId,
      user_id: 'usr_raj',
      owner_name: 'Raj Sharma',
      type: 'PPF',
      title: 'Public Provident Fund (PPF)',
      institution: 'ICICI Bank',
      invested_amount: 400000,
      current_value: 530000,
      gain_loss: 130000,
      folio_number: 'PPF-0029182',
      nominee: 'Priya Sharma',
      notes: 'Tax-free compound interest, 7.1%',
      updated_at: '2026-09-01T00:00:00Z',
    },
  ];

  // 8. Insurance
  const insurancePolicies = [
    {
      id: 'ins_1',
      family_id: familyId,
      user_id: 'usr_raj',
      insured_person: 'Entire Family (Floater)',
      policy_type: 'HEALTH',
      provider: 'HDFC ERGO Optima Secure',
      policy_number: 'HDFC-HLT-2024-9182',
      sum_insured: 1500000,
      premium_amount: 28400,
      renewal_date: '2027-03-15',
      nominee: 'Priya Sharma',
      status: 'ACTIVE',
      created_at: '2024-03-15T00:00:00Z',
    },
    {
      id: 'ins_2',
      family_id: familyId,
      user_id: 'usr_raj',
      insured_person: 'Honda City (TS09FA4021)',
      policy_type: 'VEHICLE',
      provider: 'ICICI Lombard Comprehensive',
      policy_number: 'ICICI-MOT-882910',
      sum_insured: 750000,
      premium_amount: 14200,
      renewal_date: '2026-09-21', // Due in 12 days!
      nominee: 'Raj Sharma',
      status: 'EXPIRING_SOON',
      created_at: '2025-09-21T00:00:00Z',
    },
    {
      id: 'ins_3',
      family_id: familyId,
      user_id: 'usr_raj',
      insured_person: 'Raj Sharma',
      policy_type: 'LIFE',
      provider: 'Max Life Smart Term Plan',
      policy_number: 'MAX-TRM-771920',
      sum_insured: 15000000, // 1.5 Cr
      premium_amount: 18500,
      renewal_date: '2026-11-10',
      nominee: 'Priya Sharma (100%)',
      status: 'ACTIVE',
      created_at: '2023-11-10T00:00:00Z',
    },
  ];

  // 9. Liabilities
  const liabilities = [
    {
      id: 'lia_1',
      family_id: familyId,
      user_id: 'usr_raj',
      owner_name: 'Raj & Priya',
      type: 'HOME_LOAN',
      title: 'Aparna CyberLife Apartment Loan',
      lender: 'State Bank of India',
      total_loan: 4500000,
      outstanding_amount: 1850000,
      monthly_emi: 42000,
      interest_rate: 8.5,
      end_date: '2031-08-01',
      created_at: '2021-08-01T00:00:00Z',
    },
    {
      id: 'lia_2',
      family_id: familyId,
      user_id: 'usr_raj',
      owner_name: 'Raj Sharma',
      type: 'VEHICLE_LOAN',
      title: 'Honda City Auto Loan',
      lender: 'HDFC Bank',
      total_loan: 800000,
      outstanding_amount: 150000,
      monthly_emi: 16500,
      interest_rate: 7.9,
      end_date: '2027-02-01',
      created_at: '2023-02-01T00:00:00Z',
    },
  ];

  // 10. Goals
  const goals = [
    {
      id: 'goal_1',
      family_id: familyId,
      title: 'Emergency Reserve Fund (6 Months Expenses)',
      category: 'EMERGENCY_FUND',
      target_amount: 500000,
      current_amount: 320000,
      monthly_contribution: 15000,
      target_date: '2026-12-31',
      priority: 'HIGH',
      status: 'IN_PROGRESS',
      contributors: JSON.stringify(['Raj', 'Priya']),
      created_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'goal_2',
      family_id: familyId,
      title: 'Aarav Higher Education Corpus',
      category: 'EDUCATION',
      target_amount: 1500000,
      current_amount: 850000,
      monthly_contribution: 25000,
      target_date: '2029-06-01',
      priority: 'HIGH',
      status: 'IN_PROGRESS',
      contributors: JSON.stringify(['Raj', 'Priya']),
      created_at: '2023-01-01T00:00:00Z',
    },
    {
      id: 'goal_3',
      family_id: familyId,
      title: 'Family Summer Vacation (Switzerland / Goa)',
      category: 'VACATION',
      target_amount: 100000,
      current_amount: 65000,
      monthly_contribution: 10000,
      target_date: '2027-05-15',
      priority: 'MEDIUM',
      status: 'IN_PROGRESS',
      contributors: JSON.stringify(['Raj', 'Priya', 'Aarav']),
      created_at: '2024-06-01T00:00:00Z',
    },
  ];

  // 11. Calendar Events
  const calendarEvents = [
    {
      id: 'evt_1',
      family_id: familyId,
      created_by_id: 'usr_raj',
      title: 'Car Insurance Renewal Deadline 🚗',
      type: 'INSURANCE',
      start_date: '2026-09-21',
      is_all_day: true,
      assigned_member_id: 'usr_raj',
      assigned_member_name: 'Raj',
      is_recurring: false,
      visibility: 'FAMILY',
      notes: 'ICICI Lombard Policy TS09FA4021 due for renewal',
      created_at: '2026-09-01T00:00:00Z',
    },
    {
      id: 'evt_2',
      family_id: familyId,
      created_by_id: 'usr_raj',
      title: 'TSSPDCL Electricity Bill Due Tomorrow ⚡',
      type: 'BILL',
      start_date: '2026-09-10',
      is_all_day: true,
      assigned_member_id: 'usr_raj',
      assigned_member_name: 'Raj',
      is_recurring: false,
      visibility: 'FAMILY',
      notes: 'Amount ₹3,840 via UPI',
      created_at: '2026-09-01T00:00:00Z',
    },
    {
      id: 'evt_3',
      family_id: familyId,
      created_by_id: 'usr_priya',
      title: "Mom's Birthday & Family Dinner 🎂",
      type: 'BIRTHDAY',
      start_date: '2026-09-22',
      is_all_day: true,
      assigned_member_name: 'All Family',
      is_recurring: true,
      visibility: 'FAMILY',
      notes: 'Table booked at Feast, Sheraton Hotel at 7:30 PM',
      created_at: '2026-09-01T00:00:00Z',
    },
    {
      id: 'evt_4',
      family_id: familyId,
      created_by_id: 'usr_aarav',
      title: 'Aarav Science Olympiad & Project Submission 🔬',
      type: 'SCHOOL',
      start_date: '2026-09-12',
      is_all_day: false,
      assigned_member_id: 'usr_aarav',
      assigned_member_name: 'Aarav',
      is_recurring: false,
      visibility: 'FAMILY',
      notes: 'Solar cell circuit model submission',
      created_at: '2026-09-01T00:00:00Z',
    },
    {
      id: 'evt_5',
      family_id: familyId,
      created_by_id: 'usr_raj',
      title: 'SBI Fixed Deposit Maturity (₹5,00,000) 🏦',
      type: 'SIP',
      start_date: '2026-09-24',
      is_all_day: true,
      assigned_member_id: 'usr_raj',
      assigned_member_name: 'Raj',
      is_recurring: false,
      visibility: 'FAMILY',
      notes: 'Review reinvestment in higher yield instrument',
      created_at: '2026-09-01T00:00:00Z',
    },
  ];

  // 12. Reminders
  const reminders = [
    {
      id: 'rem_1',
      family_id: familyId,
      title: 'ICICI Lombard Car Insurance expires in 12 days',
      due_date: '2026-09-21',
      category: 'INSURANCE',
      lead_days: 12,
      is_dismissed: false,
      created_at: '2026-09-01T00:00:00Z',
    },
    {
      id: 'rem_2',
      family_id: familyId,
      title: 'Electricity Bill due tomorrow (₹3,840)',
      due_date: '2026-09-10',
      category: 'BILL',
      lead_days: 1,
      is_dismissed: false,
      created_at: '2026-09-08T00:00:00Z',
    },
    {
      id: 'rem_3',
      family_id: familyId,
      title: 'Raj Passport renewal in 45 days (Passport Office Gachibowli)',
      due_date: '2026-10-24',
      category: 'DOCUMENT',
      lead_days: 45,
      is_dismissed: false,
      created_at: '2026-09-01T00:00:00Z',
    },
    {
      id: 'rem_4',
      family_id: familyId,
      title: 'SIP Auto-debit scheduled for 10th Sep (₹25,000)',
      due_date: '2026-09-10',
      category: 'SIP',
      lead_days: 1,
      is_dismissed: false,
      created_at: '2026-09-01T00:00:00Z',
    },
  ];

  // 13. Document Categories
  const documentCategories = [
    { id: 'doc_identity', name: 'Identity & Govt IDs', icon: 'Fingerprint', is_sensitive: true },
    { id: 'doc_passport', name: 'Passports & Visas', icon: 'Globe', is_sensitive: true },
    { id: 'doc_insurance', name: 'Insurance Policies', icon: 'Shield', is_sensitive: false },
    { id: 'doc_property', name: 'Property & Housing', icon: 'Home', is_sensitive: true },
    { id: 'doc_vehicle', name: 'Vehicle & RC', icon: 'Car', is_sensitive: false },
    { id: 'doc_medical', name: 'Medical & Prescriptions', icon: 'Activity', is_sensitive: false },
    { id: 'doc_education', name: 'School & Certificates', icon: 'Award', is_sensitive: false },
    { id: 'doc_financial', name: 'Tax & Financial Records', icon: 'FileText', is_sensitive: true },
  ];

  // 14. Documents
  const documents = [
    {
      id: 'doc_1',
      family_id: familyId,
      uploaded_by_id: 'usr_raj',
      owner_name: 'Raj Sharma',
      title: 'Indian Passport — Raj',
      category_id: 'doc_passport',
      document_number: 'Z4928104',
      issue_date: '2016-10-25',
      expiry_date: '2026-10-24', // Expiring in 45 days
      issuer: 'Ministry of External Affairs, India',
      file_url: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600',
      file_type: 'PDF',
      file_size_kb: 1420,
      tags: 'passport, travel, identity, raj',
      notes: 'Renewal required before international trip',
      ocr_extracted_text: 'REPUBLIC OF INDIA PASSPORT Z4928104 RAJ SHARMA EXPIRY 24/10/2026',
      is_verified: true,
      created_at: '2024-01-10T00:00:00Z',
    },
    {
      id: 'doc_2',
      family_id: familyId,
      uploaded_by_id: 'usr_raj',
      owner_name: 'Raj Sharma',
      title: 'Aadhaar Card — Raj',
      category_id: 'doc_identity',
      document_number: '•••• •••• 8492',
      issue_date: '2018-02-10',
      expiry_date: '',
      issuer: 'UIDAI',
      file_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600',
      file_type: 'PDF',
      file_size_kb: 890,
      tags: 'aadhaar, identity, govt, kyc',
      notes: 'Linked with mobile and PAN',
      ocr_extracted_text: 'GOVERNMENT OF INDIA UNIQUE IDENTIFICATION AUTHORITY OF INDIA RAJ SHARMA',
      is_verified: true,
      created_at: '2024-01-10T00:00:00Z',
    },
    {
      id: 'doc_3',
      family_id: familyId,
      uploaded_by_id: 'usr_priya',
      owner_name: 'Priya Sharma',
      title: 'PAN Card — Priya',
      category_id: 'doc_identity',
      document_number: 'ABCPS••••K',
      issue_date: '2019-07-14',
      expiry_date: '',
      issuer: 'Income Tax Department',
      file_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600',
      file_type: 'PDF',
      file_size_kb: 750,
      tags: 'pan, tax, kyc, priya',
      notes: 'Verified KYC',
      ocr_extracted_text: 'INCOME TAX DEPARTMENT GOVT OF INDIA PRIYA SHARMA',
      is_verified: true,
      created_at: '2024-01-10T00:00:00Z',
    },
    {
      id: 'doc_4',
      family_id: familyId,
      uploaded_by_id: 'usr_raj',
      owner_name: 'Family',
      title: 'HDFC ERGO Health Insurance Policy Schedule',
      category_id: 'doc_insurance',
      document_number: 'HDFC-HLT-2024-9182',
      issue_date: '2024-03-15',
      expiry_date: '2027-03-15',
      issuer: 'HDFC ERGO General Insurance',
      file_url: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=600',
      file_type: 'PDF',
      file_size_kb: 2300,
      tags: 'health, insurance, medical, family, hospital',
      notes: 'Sum insured ₹15L with Restore Benefit. Cashless at Apollo & Care hospitals.',
      ocr_extracted_text: 'HDFC ERGO OPTIMA SECURE FAMILY FLOATER COVERAGE INR 15,00,000 EXPIRY 15/03/2027',
      is_verified: true,
      created_at: '2024-03-16T00:00:00Z',
    },
    {
      id: 'doc_5',
      family_id: familyId,
      uploaded_by_id: 'usr_raj',
      owner_name: 'Raj & Priya',
      title: 'Apartment Sale Deed & Registered Conveyance',
      category_id: 'doc_property',
      document_number: 'HYD-REG-2021-492',
      issue_date: '2021-08-10',
      expiry_date: '',
      issuer: 'Sub-Registrar Office, Serilingampally',
      file_url: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=600',
      file_type: 'PDF',
      file_size_kb: 4500,
      tags: 'property, house, deed, flat, aparna',
      notes: 'Original in SBI Bank Locker',
      ocr_extracted_text: 'DEED OF SALE APARNA CYBERLIFE FLAT 402 HYDERABAD',
      is_verified: true,
      created_at: '2024-01-15T00:00:00Z',
    },
  ];

  // 15. Emergency Contacts & Profiles
  const emergencyContacts = [
    {
      id: 'emg_1',
      family_id: familyId,
      name: 'Dr. K. Srinivas Rao (Family Doctor)',
      relationship: 'Consultant Physician / Pediatrician',
      phone: '+91 94401 23456',
      secondary_phone: '+91 40 2345 6789',
      email: 'dr.srinivas@apolloclinic.com',
      type: 'DOCTOR',
      address: 'Apollo Clinic, Plot 14, Gachibowli',
      is_primary: true,
      created_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'emg_2',
      family_id: familyId,
      name: 'Apollo Hospital Emergency ER',
      relationship: 'Emergency Medical Hospital',
      phone: '1066',
      secondary_phone: '+91 40 2360 7777',
      type: 'HOSPITAL',
      address: 'Road No 72, Jubilee Hills, Hyderabad',
      is_primary: true,
      created_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'emg_3',
      family_id: familyId,
      name: 'Suresh Sharma (Brother / Uncle)',
      relationship: "Raj's Brother",
      phone: '+91 98490 88776',
      secondary_phone: '',
      email: 'suresh.sharma@example.com',
      type: 'PERSONAL',
      address: 'Banjara Hills, Hyderabad',
      is_primary: false,
      created_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'emg_4',
      family_id: familyId,
      name: 'HDFC ERGO Cashless TPA Desk',
      relationship: 'Health Insurance Claims',
      phone: '1800 2666',
      secondary_phone: '022 6234 6234',
      type: 'INSURANCE',
      address: 'Policy: HDFC-HLT-2024-9182',
      is_primary: false,
      created_at: '2024-01-01T00:00:00Z',
    },
  ];

  const emergencyProfiles = [
    {
      id: 'ep_raj',
      family_id: familyId,
      user_id: 'usr_raj',
      full_name: 'Raj Sharma',
      blood_group: 'O+',
      allergies: 'None',
      chronic_conditions: 'Mild astigmatism',
      medications: 'None',
      primary_doctor: 'Dr. K. Srinivas Rao',
      insurance_summary: 'HDFC ERGO Floater 15L, Max Life Term 1.5Cr',
      special_instructions: 'Contact Priya Sharma immediately.',
      updated_at: new Date().toISOString(),
    },
    {
      id: 'ep_priya',
      family_id: familyId,
      user_id: 'usr_priya',
      full_name: 'Priya Sharma',
      blood_group: 'B+',
      allergies: 'Dust & Sulfa drugs',
      chronic_conditions: 'None',
      medications: 'Daily Vitamin D3',
      primary_doctor: 'Dr. K. Srinivas Rao',
      insurance_summary: 'HDFC ERGO Floater 15L',
      special_instructions: 'Sulfa allergy caution for any prescription.',
      updated_at: new Date().toISOString(),
    },
    {
      id: 'ep_kalyani',
      family_id: familyId,
      user_id: 'usr_kalyani',
      full_name: 'Kalyani Sharma (Grandmother)',
      blood_group: 'B+',
      allergies: 'Penicillin (Severe)',
      chronic_conditions: 'Hypertension, Osteoarthritis in left knee',
      medications: 'Telmisartan 40mg (Morning), Shelcal 500 (Afternoon)',
      primary_doctor: 'Dr. P. V. Raman (Cardiologist, Care Hospital)',
      insurance_summary: 'Star Senior Citizens Red Carpet (5L)',
      special_instructions: 'CRITICAL: DO NOT ADMINISTER PENICILLIN. Keep BP medication handy.',
      updated_at: new Date().toISOString(),
    },
    {
      id: 'ep_aarav',
      family_id: familyId,
      user_id: 'usr_aarav',
      full_name: 'Aarav Sharma',
      blood_group: 'O+',
      allergies: 'Peanuts (Mild hives)',
      chronic_conditions: 'None',
      medications: 'Cetirizine when needed',
      primary_doctor: 'Dr. K. Srinivas Rao',
      insurance_summary: 'HDFC ERGO Floater 15L',
      special_instructions: 'Oakridge School Emergency Contact: Raj Sharma (+91 98765 43210)',
      updated_at: new Date().toISOString(),
    },
    {
      id: 'ep_ananya',
      family_id: familyId,
      user_id: 'usr_ananya',
      full_name: 'Ananya Sharma',
      blood_group: 'A+',
      allergies: 'None',
      chronic_conditions: 'None',
      medications: 'None',
      primary_doctor: 'Dr. K. Srinivas Rao',
      insurance_summary: 'HDFC ERGO Floater 15L',
      special_instructions: 'Oakridge School Student ID: OAK-2024-88',
      updated_at: new Date().toISOString(),
    },
  ];

  // 16. Memories & Voice Memories (Real memories only, no dummy seed data)
  const memories: any[] = [];
  const voiceMemories: any[] = [];

  // 17. Tasks
  const tasks = [
    {
      id: 'tsk_1',
      family_id: familyId,
      title: 'Pay TSSPDCL Electricity Bill (₹3,840) ⚡',
      category: 'BILL',
      priority: 'HIGH',
      status: 'PENDING',
      assigned_to_id: 'usr_raj',
      assigned_to_name: 'Raj',
      due_date: '2026-09-10',
      is_recurring: true,
      created_at: '2026-09-01T00:00:00Z',
    },
    {
      id: 'tsk_2',
      family_id: familyId,
      title: 'Book Daikin AC Pre-servicing before festival season ❄️',
      category: 'MAINTENANCE',
      priority: 'MEDIUM',
      status: 'PENDING',
      assigned_to_id: 'usr_raj',
      assigned_to_name: 'Raj',
      due_date: '2026-09-15',
      is_recurring: false,
      created_at: '2026-09-02T00:00:00Z',
    },
    {
      id: 'tsk_3',
      family_id: familyId,
      title: 'Complete 9th Grade Science Journal & Circuit Model 📚',
      category: 'SCHOOL',
      priority: 'HIGH',
      status: 'IN_PROGRESS',
      assigned_to_id: 'usr_aarav',
      assigned_to_name: 'Aarav',
      due_date: '2026-09-12',
      is_recurring: false,
      created_at: '2026-09-05T00:00:00Z',
    },
    {
      id: 'tsk_4',
      family_id: familyId,
      title: 'Pick up Dadi Monthly Blood Pressure Medicines from Apollo 💊',
      category: 'CHORE',
      priority: 'HIGH',
      status: 'COMPLETED',
      assigned_to_id: 'usr_priya',
      assigned_to_name: 'Priya',
      due_date: '2026-09-07',
      is_recurring: true,
      completed_at: '2026-09-07T11:00:00Z',
      created_at: '2026-09-01T00:00:00Z',
    },
  ];

  // 18. Grocery Items
  const groceryItems = [
    { id: 'g_1', family_id: familyId, item_name: 'Aashirvaad Shudh Chakki Atta (10kg)', quantity: '1 pack', category: 'STAPLES', is_purchased: false, added_by_name: 'Priya', created_at: new Date().toISOString() },
    { id: 'g_2', family_id: familyId, item_name: 'Heritage / Nandini Toned Milk', quantity: '2 Litres', category: 'DAIRY', is_purchased: true, added_by_name: 'Raj', created_at: new Date().toISOString() },
    { id: 'g_3', family_id: familyId, item_name: 'Organic Tomatoes & Baby Spinach', quantity: '1.5 kg', category: 'PRODUCE', is_purchased: false, added_by_name: 'Priya', created_at: new Date().toISOString() },
    { id: 'g_4', family_id: familyId, item_name: 'California Almonds & Walnuts', quantity: '500g each', category: 'SNACKS', is_purchased: false, added_by_name: 'Kalyani', created_at: new Date().toISOString() },
    { id: 'g_5', family_id: familyId, item_name: 'Vim Dishwasher Gel & Sponge Scrubbers', quantity: '1 bottle', category: 'HOUSEHOLD', is_purchased: true, added_by_name: 'Priya', created_at: new Date().toISOString() },
  ];

  // 19. Household Maintenance
  const maintenanceItems = [
    {
      id: 'maint_1',
      family_id: familyId,
      item_name: 'Living Room Daikin 1.5T Inverter AC',
      service_type: 'AC',
      last_service_date: '2026-03-15',
      next_service_due: '2026-09-15',
      service_provider: 'Urban Company Daikin Specialist',
      contact_phone: '+91 98480 11223',
      recurring_interval_months: 6,
      notes: 'Deep jet clean & filter check',
    },
    {
      id: 'maint_2',
      family_id: familyId,
      item_name: 'Honda City TS09FA4021 (20k km service)',
      service_type: 'CAR',
      last_service_date: '2026-01-20',
      next_service_due: '2026-10-10',
      service_provider: 'Sundaram Honda, Kondapur',
      contact_phone: '+91 40 4455 6677',
      recurring_interval_months: 9,
      notes: 'Engine oil change, wheel alignment and brake pads',
    },
    {
      id: 'maint_3',
      family_id: familyId,
      item_name: 'Kent Grand Plus RO Water Purifier',
      service_type: 'RO_FILTER',
      last_service_date: '2026-04-10',
      next_service_due: '2026-10-15',
      service_provider: 'Kent Authorized Care',
      contact_phone: '1800 100 1001',
      recurring_interval_months: 6,
      notes: 'Sediment and carbon filter replacement',
    },
  ];

  // 20. Notifications
  const notifications = [
    {
      id: 'notif_1',
      family_id: familyId,
      title: '🔴 Insurance Renewal Alert',
      message: 'ICICI Lombard Vehicle Insurance for Honda City expires in 12 days (21 Sep). Renew to prevent policy lapse.',
      type: 'URGENT',
      link_tab: 'vault',
      is_read: false,
      created_at: '2026-09-09T08:00:00Z',
    },
    {
      id: 'notif_2',
      family_id: familyId,
      title: '🟠 Electricity Bill Due Tomorrow',
      message: 'TSSPDCL electricity bill of ₹3,840 is due on 10 Sep. Avoid late surcharge.',
      type: 'WARNING',
      link_tab: 'money',
      is_read: false,
      created_at: '2026-09-09T09:30:00Z',
    },
    {
      id: 'notif_3',
      family_id: familyId,
      title: '🟢 SIP Investment Processed',
      message: '₹25,000 monthly SIP has been credited into Parag Parikh and Mirae Asset funds.',
      type: 'SUCCESS',
      link_tab: 'money',
      is_read: true,
      created_at: '2026-09-08T10:00:00Z',
    },
    {
      id: 'notif_4',
      family_id: familyId,
      title: '🤖 FamilyAI Insight',
      message: 'Your grocery spending is 18% higher than your 3-month average. You could save approx ₹2,300 by trimming non-essentials.',
      type: 'INFO',
      link_tab: 'ai',
      is_read: false,
      created_at: '2026-09-09T06:00:00Z',
    },
  ];

  // 17. Family & Friends Contacts & Occasions
  const familyContacts = [
    {
      id: 'cnt_ravi_kumar',
      family_id: familyId,
      name: 'Ravi Kumar',
      photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300',
      mobile_number: '+91 98765 43210',
      relationship: 'Uncle',
      notes: 'Likes books, filter coffee, and traditional Indian sweets.',
      visibility: 'FAMILY',
      visible_to_members: [],
      created_by: 'usr_raj',
      created_at: new Date('2024-01-01').toISOString(),
      updated_at: new Date().toISOString(),
      is_active: true,
    },
    {
      id: 'cnt_priya_nandini',
      family_id: familyId,
      name: 'Priya Nandini',
      photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300',
      mobile_number: '+91 98765 88990',
      relationship: 'Cousin',
      notes: 'Loves dark chocolate, fiction novels, and classical music.',
      visibility: 'FAMILY',
      visible_to_members: [],
      created_by: 'usr_priya',
      created_at: new Date('2024-01-05').toISOString(),
      updated_at: new Date().toISOString(),
      is_active: true,
    },
    {
      id: 'cnt_sita_raj',
      family_id: familyId,
      name: 'Raj & Sita Verma',
      photo_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300',
      mobile_number: '+91 98480 12345',
      relationship: 'Family Friend',
      notes: 'Always invite for Diwali family lunch.',
      visibility: 'FAMILY',
      visible_to_members: [],
      created_by: 'usr_raj',
      created_at: new Date('2024-01-10').toISOString(),
      updated_at: new Date().toISOString(),
      is_active: true,
    },
    {
      id: 'cnt_vikram_varma',
      family_id: familyId,
      name: 'Vikram Varma',
      photo_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300',
      mobile_number: '+91 94401 55667',
      relationship: 'Colleague',
      notes: 'Loves badminton and tech podcasts.',
      visibility: 'FAMILY',
      visible_to_members: [],
      created_by: 'usr_raj',
      created_at: new Date('2024-02-01').toISOString(),
      updated_at: new Date().toISOString(),
      is_active: true,
    },
  ];

  const familyContactOccasions = [
    {
      id: 'occ_ravi_bday',
      contact_id: 'cnt_ravi_kumar',
      family_id: familyId,
      occasion_type: 'BIRTHDAY',
      custom_occasion_name: 'Birthday',
      occasion_date: '1985-09-25',
      original_year: 1985,
      is_recurring: true,
      reminder_type: 'OFFSET_DAYS',
      reminder_days_before: 7,
      is_active: true,
      created_at: new Date('2024-01-01').toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'occ_ravi_anniv',
      contact_id: 'cnt_ravi_kumar',
      family_id: familyId,
      occasion_type: 'MARRIAGE_ANNIVERSARY',
      custom_occasion_name: 'Marriage Anniversary',
      occasion_date: '2010-02-12',
      original_year: 2010,
      is_recurring: true,
      reminder_type: 'OFFSET_DAYS',
      reminder_days_before: 7,
      is_active: true,
      created_at: new Date('2024-01-01').toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'occ_priya_bday',
      contact_id: 'cnt_priya_nandini',
      family_id: familyId,
      occasion_type: 'BIRTHDAY',
      custom_occasion_name: 'Birthday',
      occasion_date: '1994-09-21',
      original_year: 1994,
      is_recurring: true,
      reminder_type: 'OFFSET_DAYS',
      reminder_days_before: 5,
      is_active: true,
      created_at: new Date('2024-01-05').toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'occ_sita_anniv',
      contact_id: 'cnt_sita_raj',
      family_id: familyId,
      occasion_type: 'MARRIAGE_ANNIVERSARY',
      custom_occasion_name: 'Marriage Anniversary',
      occasion_date: '2015-10-03',
      original_year: 2015,
      is_recurring: true,
      reminder_type: 'OFFSET_DAYS',
      reminder_days_before: 14,
      is_active: true,
      created_at: new Date('2024-01-10').toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'occ_vikram_bday',
      contact_id: 'cnt_vikram_varma',
      family_id: familyId,
      occasion_type: 'BIRTHDAY',
      custom_occasion_name: 'Birthday',
      occasion_date: '1990-11-18',
      original_year: 1990,
      is_recurring: true,
      reminder_type: 'OFFSET_DAYS',
      reminder_days_before: 3,
      is_active: true,
      created_at: new Date('2024-02-01').toISOString(),
      updated_at: new Date().toISOString(),
    },
  ];

  const reminderSettings = [
    {
      id: 'rem_set_1',
      occasion_id: 'occ_ravi_bday',
      dashboard_enabled: true,
      push_notification_enabled: true,
      notification_frequency: 'DAILY',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'rem_set_2',
      occasion_id: 'occ_ravi_anniv',
      dashboard_enabled: true,
      push_notification_enabled: true,
      notification_frequency: 'DAILY',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'rem_set_3',
      occasion_id: 'occ_priya_bday',
      dashboard_enabled: true,
      push_notification_enabled: true,
      notification_frequency: 'DAILY',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'rem_set_4',
      occasion_id: 'occ_sita_anniv',
      dashboard_enabled: true,
      push_notification_enabled: true,
      notification_frequency: 'DAILY',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ];

  db.resetData({
    families,
    users,
    permissions: permissionsList,
    member_permissions: memberPermissions,
    devices: [
      {
        id: 'dev_1',
        user_id: 'usr_raj',
        device_name: 'iPhone 15 Pro Max',
        device_type: 'MOBILE',
        platform: 'iOS',
        browser: 'Safari Mobile',
        os: 'iOS 17.4',
        ip_address: '157.48.12.98 (Hyderabad)',
        last_active: 'Just now',
        is_current: true,
        is_trusted: true,
      },
    ],
    audit_logs: [
      {
        id: 'aud_1',
        family_id: familyId,
        user_id: 'usr_raj',
        user_name: 'Raj Sharma',
        action: 'Created Sharma Family Account',
        category: 'ADMIN',
        details: 'Initial family vault, encryption key, and accounts generated.',
        created_at: '2024-01-01T00:00:00Z',
      },
      {
        id: 'aud_2',
        family_id: familyId,
        user_id: 'usr_priya',
        user_name: 'Priya Sharma',
        action: 'Added Monthly Grocery Expense',
        category: 'FINANCE',
        details: 'Logged ₹14,200 at Ratnadeep Supermarket via UPI.',
        created_at: '2026-09-04T11:20:00Z',
      },
      {
        id: 'aud_3',
        family_id: familyId,
        user_id: 'usr_raj',
        user_name: 'Raj Sharma',
        action: 'Viewed Emergency Vault',
        category: 'EMERGENCY',
        details: 'Checked Grandmother Kalyani medication and allergy notes.',
        created_at: '2026-09-08T14:10:00Z',
      },
    ],
    expense_categories: expenseCategories,
    expenses,
    budgets,
    investments,
    insurance_policies: insurancePolicies,
    liabilities,
    goals,
    calendar_events: calendarEvents,
    reminders,
    document_categories: documentCategories,
    documents,
    emergency_contacts: emergencyContacts,
    emergency_profiles: emergencyProfiles,
    memories,
    voice_memories: voiceMemories,
    tasks,
    grocery_items: groceryItems,
    maintenance_items: maintenanceItems,
    notifications,
    ai_conversations: [],
    detected_transactions: [],
    merchant_aliases: [],
    merchant_preferences: [],
    smart_capture_settings: [],
    family_contacts: familyContacts,
    family_contact_occasions: familyContactOccasions,
    reminder_settings: reminderSettings,
    contact_permissions: [],
  });

  console.log('✅ Sharma Family Demo dataset seeded successfully with full cross-module records.');
}

if (process.argv[1]?.endsWith('seed.ts') || process.argv[1]?.endsWith('seed.js')) {
  seedDatabase();
}
